export const mockUsers = [
  {
    id: "user_1",
    username: "alex_debates",
    email: "alex@example.com",
    bio: "Philosophy enthusiast and AI researcher",
    avatarUrl: null,
    reputationScore: 2340,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "user_2",
    username: "techphilosopher",
    email: "tech@example.com",
    bio: "Exploring the intersection of technology and ethics",
    avatarUrl: null,
    reputationScore: 5820,
    createdAt: new Date("2023-11-20"),
  },
  {
    id: "user_3",
    username: "debate_queen",
    email: "queen@example.com",
    bio: "Oxford debater, logic lover",
    avatarUrl: null,
    reputationScore: 8940,
    createdAt: new Date("2023-08-10"),
  },
  {
    id: "user_4",
    username: "sciencemind",
    email: "science@example.com",
    bio: "Evidence-based thinker",
    avatarUrl: null,
    reputationScore: 1230,
    createdAt: new Date("2024-03-05"),
  },
];

export const mockDebates = [
  {
    id: "debate_1",
    title: "Should AI be regulated like nuclear technology?",
    description:
      "As AI systems grow more powerful, should governments impose strict controls similar to those used for nuclear technology — including international treaties, licensing, and kill switches?",
    category: "AI",
    tags: ["artificial intelligence", "regulation", "policy", "safety"],
    authorId: "user_1",
    author: mockUsers[0],
    participantCount: 234,
    argCount: 89,
    proVotes: 156,
    conVotes: 78,
    createdAt: new Date("2024-06-10"),
    updatedAt: new Date("2024-06-12"),
  },
  {
    id: "debate_2",
    title: "Remote work permanently outperforms office work",
    description:
      "The pandemic proved that remote work can be just as — or more — productive than in-office work. Should companies adopt fully remote policies as the default?",
    category: "Technology",
    tags: ["remote work", "productivity", "work culture"],
    authorId: "user_2",
    author: mockUsers[1],
    participantCount: 412,
    argCount: 143,
    proVotes: 289,
    conVotes: 123,
    createdAt: new Date("2024-06-08"),
    updatedAt: new Date("2024-06-11"),
  },
  {
    id: "debate_3",
    title: "Universal Basic Income will harm economic productivity",
    description:
      "Critics argue that UBI disincentivizes work and will lead to inflation. Is a guaranteed income a threat or a cure for economic inequality?",
    category: "Economics",
    tags: ["UBI", "economics", "welfare", "inequality"],
    authorId: "user_3",
    author: mockUsers[2],
    participantCount: 678,
    argCount: 211,
    proVotes: 198,
    conVotes: 480,
    createdAt: new Date("2024-06-05"),
    updatedAt: new Date("2024-06-10"),
  },
  {
    id: "debate_4",
    title: "Social media platforms should be liable for user content",
    description:
      "Should Section 230 protections be removed, making platforms legally responsible for harmful content posted by users?",
    category: "Technology",
    tags: ["social media", "law", "section 230", "free speech"],
    authorId: "user_1",
    author: mockUsers[0],
    participantCount: 321,
    argCount: 95,
    proVotes: 210,
    conVotes: 111,
    createdAt: new Date("2024-06-03"),
    updatedAt: new Date("2024-06-09"),
  },
  {
    id: "debate_5",
    title: "Consciousness is purely a product of physical brain processes",
    description:
      "Is the mind nothing more than neural activity? Or does consciousness require something beyond the physical — a soul, qualia, or emergent properties?",
    category: "Philosophy",
    tags: ["consciousness", "mind", "philosophy of mind", "neuroscience"],
    authorId: "user_2",
    author: mockUsers[1],
    participantCount: 189,
    argCount: 67,
    proVotes: 124,
    conVotes: 65,
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-06-08"),
  },
  {
    id: "debate_6",
    title: "Startups should prioritize profitability over growth",
    description:
      "The venture-backed growth-at-all-costs model has failed many companies. Is sustainable profitability a better strategy than blitzscaling?",
    category: "Startups",
    tags: ["startups", "profitability", "venture capital", "growth"],
    authorId: "user_3",
    author: mockUsers[2],
    participantCount: 267,
    argCount: 78,
    proVotes: 198,
    conVotes: 69,
    createdAt: new Date("2024-05-28"),
    updatedAt: new Date("2024-06-07"),
  },
  {
    id: "debate_7",
    title: "Gene editing in humans should be fully permitted",
    description:
      "With CRISPR technology advancing rapidly, should we allow germline editing to eliminate hereditary diseases — or does this open the door to designer babies?",
    category: "Science",
    tags: ["CRISPR", "genetics", "bioethics", "medicine"],
    authorId: "user_4",
    author: mockUsers[3],
    participantCount: 445,
    argCount: 167,
    proVotes: 287,
    conVotes: 158,
    createdAt: new Date("2024-05-25"),
    updatedAt: new Date("2024-06-06"),
  },
  {
    id: "debate_8",
    title: "Nuclear energy is essential for climate goals",
    description:
      "Given the urgency of climate change, should nations massively expand nuclear power generation despite safety concerns and high costs?",
    category: "Science",
    tags: ["nuclear energy", "climate", "energy policy", "sustainability"],
    authorId: "user_1",
    author: mockUsers[0],
    participantCount: 534,
    argCount: 192,
    proVotes: 389,
    conVotes: 145,
    createdAt: new Date("2024-05-20"),
    updatedAt: new Date("2024-06-05"),
  },
  {
    id: "debate_9",
    title: "Democracy is the worst system except all others",
    description:
      "Churchill's famous quip prompts a real question: Are there better governance models for complex modern societies than traditional liberal democracy?",
    category: "Philosophy",
    tags: ["democracy", "governance", "political philosophy"],
    authorId: "user_2",
    author: mockUsers[1],
    participantCount: 712,
    argCount: 245,
    proVotes: 512,
    conVotes: 200,
    createdAt: new Date("2024-05-15"),
    updatedAt: new Date("2024-06-04"),
  },
  {
    id: "debate_10",
    title: "Cryptocurrencies will replace fiat currencies by 2050",
    description:
      "Decentralized digital currencies are gaining ground. Will Bitcoin and its successors render traditional government-issued money obsolete within a generation?",
    category: "Economics",
    tags: ["cryptocurrency", "bitcoin", "finance", "future"],
    authorId: "user_3",
    author: mockUsers[2],
    participantCount: 389,
    argCount: 134,
    proVotes: 156,
    conVotes: 233,
    createdAt: new Date("2024-05-10"),
    updatedAt: new Date("2024-06-03"),
  },
];

export const mockArguments = [
  {
    id: "arg_1",
    debateId: "debate_1",
    authorId: "user_2",
    author: mockUsers[1],
    content:
      "AI systems, especially large language models and autonomous agents, present existential risks similar to nuclear weapons. The concentration of this technology in the hands of a few companies without international oversight is extremely dangerous. We saw how nuclear non-proliferation treaties prevented catastrophic outcomes — a similar framework for AI is not just prudent, it's necessary.",
    side: "PRO" as const,
    parentId: null,
    upvotes: 234,
    downvotes: 12,
    evidenceCount: 3,
    createdAt: new Date("2024-06-11"),
    replies: [
      {
        id: "arg_1_reply_1",
        debateId: "debate_1",
        authorId: "user_4",
        author: mockUsers[3],
        content:
          "The analogy breaks down because nuclear weapons are purely destructive while AI has enormous beneficial applications. Regulating it like nuclear tech would stifle innovation and cede competitive advantage to nations with fewer scruples.",
        side: "CON" as const,
        parentId: "arg_1",
        upvotes: 89,
        downvotes: 34,
        evidenceCount: 1,
        createdAt: new Date("2024-06-11"),
        replies: [],
      },
    ],
  },
  {
    id: "arg_2",
    debateId: "debate_1",
    authorId: "user_3",
    author: mockUsers[2],
    content:
      "The pace of AI development far exceeds our governance capacity. We already have the EU AI Act as a precedent. The question isn't whether to regulate — it's whether current proposals go far enough. Mandatory capability evaluations, incident reporting, and international coordination are the bare minimum.",
    side: "PRO" as const,
    parentId: null,
    upvotes: 178,
    downvotes: 23,
    evidenceCount: 5,
    createdAt: new Date("2024-06-11"),
    replies: [],
  },
  {
    id: "arg_3",
    debateId: "debate_1",
    authorId: "user_1",
    author: mockUsers[0],
    content:
      "Regulating AI like nuclear technology is a category error. Nuclear reactions are physically dangerous by nature. AI software is contextual — the same model that writes poetry can assist in drug discovery. Heavy-handed regulation based on worst-case scenarios will prevent us from solving climate change, cancer, and poverty with AI tools.",
    side: "CON" as const,
    parentId: null,
    upvotes: 145,
    downvotes: 67,
    evidenceCount: 2,
    createdAt: new Date("2024-06-10"),
    replies: [],
  },
  {
    id: "arg_4",
    debateId: "debate_1",
    authorId: "user_4",
    author: mockUsers[3],
    content:
      "The real risk isn't the AI itself — it's misalignment and misuse by humans. We should regulate the applications and use cases, not the underlying technology. Blanket nuclear-style restrictions would be equivalent to banning the internet because it can be used for harmful purposes.",
    side: "CON" as const,
    parentId: null,
    upvotes: 123,
    downvotes: 45,
    evidenceCount: 0,
    createdAt: new Date("2024-06-10"),
    replies: [],
  },
];

export const mockNotifications = [
  {
    id: "notif_1",
    userId: "user_1",
    type: "VOTE" as const,
    message: "techphilosopher upvoted your argument in 'AI Regulation' debate",
    read: false,
    createdAt: new Date("2024-06-12T10:30:00"),
  },
  {
    id: "notif_2",
    userId: "user_1",
    type: "REPLY" as const,
    message: "debate_queen replied to your argument in 'Remote Work' debate",
    read: false,
    createdAt: new Date("2024-06-12T09:15:00"),
  },
  {
    id: "notif_3",
    userId: "user_1",
    type: "MENTION" as const,
    message: "sciencemind mentioned you in 'Gene Editing' debate",
    read: true,
    createdAt: new Date("2024-06-11T14:22:00"),
  },
  {
    id: "notif_4",
    userId: "user_1",
    type: "VOTE" as const,
    message: "Your argument received 50 upvotes! You earned +25 reputation",
    read: true,
    createdAt: new Date("2024-06-11T11:05:00"),
  },
  {
    id: "notif_5",
    userId: "user_1",
    type: "DEBATE_REPLY" as const,
    message: "New arguments added to 'UBI' debate you follow",
    read: true,
    createdAt: new Date("2024-06-10T16:45:00"),
  },
];

export const topDebaters = [
  { rank: 1, user: mockUsers[2], weeklyPoints: 892 },
  { rank: 2, user: mockUsers[1], weeklyPoints: 734 },
  { rank: 3, user: mockUsers[0], weeklyPoints: 612 },
  { rank: 4, user: mockUsers[3], weeklyPoints: 445 },
];

export const trendingTopics = [
  { tag: "AI Safety", count: 234 },
  { tag: "Climate Policy", count: 189 },
  { tag: "Crypto Regulation", count: 156 },
  { tag: "UBI", count: 143 },
  { tag: "Nuclear Energy", count: 128 },
  { tag: "Remote Work", count: 112 },
];
